INSERT INTO public.genders (id, code, name) VALUES (1, 'm', 'muž');
INSERT INTO public.genders (id, code, name) VALUES (2, 'f', 'žena');

INSERT INTO public.marital_statuses (id, code) VALUES (1, 'single');
INSERT INTO public.marital_statuses (id, code) VALUES (2, 'married');
INSERT INTO public.marital_statuses (id, code) VALUES (3, 'divorced');
INSERT INTO public.marital_statuses (id, code) VALUES (4, 'widowed');

INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (2, 1, 1, 'slobodný');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (3, 2, 1, 'ženatý');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (4, 3, 1, 'rozvedený');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (5, 4, 1, 'vdovec');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (6, 1, 2, 'slobodná');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (7, 2, 2, 'vydatá');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (8, 3, 2, 'rozvedená');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (9, 4, 2, 'vdova');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (10, 1, null, 'slobodný / slobodná');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (11, 2, null, 'ženatý / vydatá');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (12, 3, null, 'rozvedený / rozvedená');
INSERT INTO public.marital_status_names (id, marital_status_id, gender_id, name) VALUES (13, 4, null, 'vdovec / vdova');

INSERT INTO public.titles (id, name, type) VALUES (1, 'Bc.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (2, 'Mgr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (3, 'Ing.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (4, 'JUDr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (5, 'MVDr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (6, 'MUDr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (7, 'PaedDr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (8, 'prof.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (9, 'doc.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (10, 'dipl.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (11, 'MDDr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (12, 'Dr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (13, 'Mgr. art.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (14, 'ThLic.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (15, 'PhDr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (16, 'PhMr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (17, 'RNDr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (18, 'ThDr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (19, 'RSDr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (20, 'arch.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (21, 'PharmDr.', 'before_name');
INSERT INTO public.titles (id, name, type) VALUES (28, 'FEBO', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (34, 'FCCA', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (23, 'DrSc.', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (37, 'LL.M', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (32, 'DBA', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (35, 'MSc.', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (33, 'MHA', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (31, 'MBA', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (24, 'PhD.', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (36, 'FEBU', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (29, 'MPH', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (30, 'BSBA', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (22, 'CSc.', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (25, 'ArtD.', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (27, 'DiS.art', 'after_name');
INSERT INTO public.titles (id, name, type) VALUES (26, 'DiS', 'after_name');
